services:
  dev-db:
    image: postgres:15
    container_name: dev-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: nest
    ports:
      - '5434:5432'
    networks:
      - db-net
networks:
  db-net: